spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:create
    properties:
      hibernate:
        format_sql:true
#        hibernate.default_batch_fetch_size: 1000
logging:
level:
  org.hibernate.SQL: trace